create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  feedback_type text not null default 'general',
  rating integer not null default 3 check (rating between 1 and 5),
  message text not null,
  email text,
  may_contact boolean not null default false,
  profile_name text,
  page text,
  source text default 'dashboard',
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

create policy "Allow server-side feedback inserts"
on public.feedback
for insert
to service_role
with check (true);
