"use client";
import { AlertTriangle, ArrowRight, CheckCircle2, Lightbulb, TrendingUp } from "lucide-react";
import { createDailyBrief } from "@/lib/joye/context";
import type { UserContext } from "@/types/database";

const demo:UserContext={displayName:"Alex",timezone:"America/New_York",availableMinutes:45,energy:"medium",primaryFocus:"Build consistency",goals:[{id:"g1",title:"Complete a meaningful 90-day goal",progress:78}],tasks:[{id:"t1",title:"Finish the next focused project step",minutes:30,priority:5,completed:false,dueDate:new Date(Date.now()+86400000).toISOString()},{id:"t2",title:"Review this week’s plan",minutes:15,priority:3,completed:true}],money:{availableMargin:140,upcomingBills:80},career:{currentRole:"Current role",targetRole:"Next role",nextMilestone:"Document one proof-of-skill example."}};

const icon={attention:AlertTriangle,opportunity:Lightbulb,progress:TrendingUp};
export function TodayExperience(){const brief=createDailyBrief(demo);return <div className="mx-auto max-w-6xl space-y-6"><section className="card overflow-hidden"><div className="bg-ink p-6 text-white sm:p-9"><p className="text-sm text-white/50">Today</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">{brief.greeting}</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-white/65">{brief.summary}</p></div><div className="grid gap-6 p-6 sm:p-9 lg:grid-cols-[1.2fr_.8fr]"><div><p className="eyebrow">Your next move</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">{brief.recommendation.title}</h2><p className="mt-3 max-w-xl leading-7 text-black/55">{brief.recommendation.reason}</p><button className="button-primary mt-6 gap-2">{brief.recommendation.actionLabel}<ArrowRight size={16}/></button></div><div className="rounded-3xl bg-mist p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-black/40">Today’s capacity</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white p-4"><p className="text-2xl font-semibold">{demo.availableMinutes}</p><p className="mt-1 text-xs text-black/45">minutes available</p></div><div className="rounded-2xl bg-white p-4"><p className="text-2xl font-semibold capitalize">{demo.energy}</p><p className="mt-1 text-xs text-black/45">current energy</p></div></div></div></div></section><section><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Joye signals</p><h2 className="mt-2 text-2xl font-semibold">What changed and what matters</h2></div><span className="text-sm text-black/40">Live context preview</span></div><div className="grid gap-4 md:grid-cols-2">{brief.signals.map(signal=>{const Icon=icon[signal.kind];return <article key={signal.id} className="card p-5"><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-mist"><Icon size={18}/></span><div><p className="font-semibold">{signal.title}</p><p className="mt-2 text-sm leading-6 text-black/55">{signal.detail}</p></div></div></article>})}<article className="card p-5"><div className="flex gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-green-50 text-green-700"><CheckCircle2 size={18}/></span><div><p className="font-semibold">The plan is intentionally light</p><p className="mt-2 text-sm leading-6 text-black/55">Joye Life prioritizes one finishable move before adding more work.</p></div></div></article></div></section></div>}
