create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null default 'website',
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.waitlist enable row level security;

-- The website writes through the server-side Vercel function using a Supabase
-- secret/service-role key. Do not expose that key in browser JavaScript.
revoke all on table public.waitlist from anon, authenticated;
grant select, insert, update, delete on table public.waitlist to service_role;
